### ISSUE TITLE
Prevent Access to Login Page After Authentication

### ISSUE THREAD

**Issue by an-um** [10kumaranurag01/todo-done#42] opened 2024-10-03 16:33 UTC
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

On live website

### Version of website/mobile (for example "v1.2.3")

v1

### Description

Description: Currently, after a user successfully logs in and navigates to the dashboard, they can still access the login page by using the browser's back button. This behavior allows logged-in users to potentially reattempt logging in, which is not ideal for a smooth user experience.

Expected Behavior:

- Once a user is authenticated and navigates to the dashboard or any protected route, they should not be able to go back to the login page unless they log out.
- Attempting to navigate to the login page after authentication should redirect the user to the dashboard or their last visited page.

### Steps to Reproduce

If you know the steps, follow the below format and provide steps to reproduce

For example:

1. Log in with valid credentials.
2. Navigate to the dashboard or any other protected route.
3. Press the back button on the browser.

### Screenshots

![image](https://github.com/user-attachments/assets/4690ffe7-00c5-4858-84d6-232fddaa067c)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

- Implement route guards or redirection logic to prevent logged-in users from accessing the login page.
- If a user attempts to navigate to the login page after authentication, they should be redirected back to the dashboard or the appropriate protected route.

**Comment by an-um** [comment] 2024-10-03 16:34
@10kumaranurag01 I want to work on this issue. Please assign this task to me.

**Comment by 10kumaranurag01** [comment] 2024-10-03 16:38
@an-um Fork it, take a new branch and create a PR.

**Comment by SauravGupta123** [comment] 2024-10-03 17:34
please assign issue to me. I have fixed this issue many times.

**Comment by 10kumaranurag01** [comment] 2024-10-03 17:40
@SauravGupta123 Sorry, the issue is already assigned to @an-um , you can check out existing issues or create new issues if you find any. Thanks for your enthusiasm ☺️.

**Comment by an-um** [comment] 2024-10-05 08:50
@10kumaranurag01 I have resolved this issue, Please dont close this issue as I created this issue and dont assign it to other contributor. It is a humble request. Thankxx...

**Closed** 2024-10-05 12:15 UTC
Labels: bug, hacktoberfest
